lb=["zero","ra","sp","gp","tp","t0","t1","t2","s0","s1",\
    "a0","a1","a2","a3","a4","a5","a6","a7",\
    "s2","s3","s4","s5","s6","s7","s8","s9","s10","s11",\
    "t3","t4","t5","t6"]# s0/fp not considered

ld = [str(i) for i in range(len(lb))]

for i in range(len(lb)):
    print("\
    /* Codes automatically generated by python */")
    print("\
    if (strcmp(str, \""+lb[i]+"\")==0||strcmp(str, \"x"+ld[i]+"\")==0){return "+ld[i]+";}")
    
print()
print("\
    /* fp==x8 */")
print("\
    if (strcmp(str, \"fp\")==0){return 8;}")
print("\
    /* error */")
print("\
    return -1;")